export const dataVideo = [
    {
        "id": 840,
        "uuid": "c815a1d2-5598-4a75-8e36-95581f1cb141",
        "user_id": 211,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/840-63723a61b9375.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/840-63723a60f27a2.mp4",
        "description": "Hình ảnh 1 đứa nhóc bị 13 con ma hội đồng🐧[⚠️fake...!!] #honkaiimpact3rd #honkai #hoyoverse #game #anime #viral #xhtiktok #xh #fyb",
        "music": "nhạc nền - mad",
        "is_liked": false,
        "likes_count": 13,
        "comments_count": 20,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [
            "comment",
            "duet",
            "stitch"
        ],
        "published_at": "2022-11-14 19:53:52",
        "created_at": "2022-11-14 19:53:52",
        "updated_at": "2022-11-14 19:53:54",
        "user": {
            "id": 211,
            "first_name": "Đỗ",
            "last_name": "Xuân Bách",
            "nickname": "xuanbachdev",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/211/63667b3246f40.jpg",
            "bio": "Xuanbach.dev",
            "tick": false,
            "is_followed": false,
            "followings_count": 7,
            "followers_count": 47,
            "likes_count": 40,
            "website_url": "https://fullstack.edu.vn/",
            "facebook_url": "https://www.facebook.com/xuanbachh.dev",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 2123345,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "0:11",
            "playtime_seconds": 11.447,
            "bitrate": 1476664.278850354,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 1024,
                "resolution_y": 576,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 30
            }
        }
    },
    {
        "id": 838,
        "uuid": "71b717af-35b1-48a2-91be-ac17ae0563dc",
        "user_id": 4266,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/838-6371fd17d3ecd.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/838-6371fd17211a6.mp4",
        "description": "Nhót",
        "music": "",
        "is_liked": false,
        "likes_count": 7,
        "comments_count": 2,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [
            "comment"
        ],
        "published_at": "2022-11-14 15:32:23",
        "created_at": "2022-11-14 15:32:23",
        "updated_at": "2022-11-14 15:32:24",
        "user": {
            "id": 4266,
            "first_name": "Hoàng Văn",
            "last_name": "Hiệp",
            "nickname": "hiep92361",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/4266/6371fa5f1c1c2.jpg",
            "bio": "Talk less Do much",
            "tick": false,
            "is_followed": false,
            "followings_count": 4,
            "followers_count": 9,
            "likes_count": 7,
            "website_url": "https://fullstack.edu.vn/",
            "facebook_url": "",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 2394083,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "0:19",
            "playtime_seconds": 19.482,
            "bitrate": 973946.0014372241,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 576,
                "resolution_y": 1024,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 30
            }
        }
    },
    {
        "id": 835,
        "uuid": "63e3b1b0-505c-4785-9692-6744c9b63559",
        "user_id": 4261,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/835-6371c8481b784.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/835-6371c847d3a13.mp4",
        "description": "Khoái Khoái :))",
        "music": "",
        "is_liked": false,
        "likes_count": 14,
        "comments_count": 9,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [
            "comment"
        ],
        "published_at": "2022-11-14 11:47:03",
        "created_at": "2022-11-14 11:47:03",
        "updated_at": "2022-11-14 11:47:04",
        "user": {
            "id": 4261,
            "first_name": "Gumball",
            "last_name": "Darwin",
            "nickname": "gumball",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/4261/6371c82e86400.png",
            "bio": "✨ Gumball & Darwin ✨",
            "tick": false,
            "is_followed": false,
            "followings_count": 7,
            "followers_count": 11,
            "likes_count": 14,
            "website_url": "https://fullstack.edu.vn/",
            "facebook_url": "",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 1309889,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "0:14",
            "playtime_seconds": 14.025,
            "bitrate": 740095.5436720143,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 576,
                "resolution_y": 1024,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 25
            }
        }
    },
    {
        "id": 834,
        "uuid": "03560308-c16d-4c19-a81e-074c50933ef0",
        "user_id": 3998,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/834-6371c6436f86b.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/834-6371c6432c1e9.mp4",
        "description": "zxczxc",
        "music": "1",
        "is_liked": false,
        "likes_count": 5,
        "comments_count": 2,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [],
        "published_at": "2022-11-14 11:38:27",
        "created_at": "2022-11-14 11:38:27",
        "updated_at": "2022-11-14 11:38:28",
        "user": {
            "id": 3998,
            "first_name": "Trần",
            "last_name": "Toàn",
            "nickname": "tranhuutoan",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/3998/63650b54826f3.jpg",
            "bio": "https://github.com/htoann/tiktok-clone",
            "tick": false,
            "is_followed": false,
            "followings_count": 12,
            "followers_count": 11,
            "likes_count": 16,
            "website_url": "",
            "facebook_url": "",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 4984550,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "1:00",
            "playtime_seconds": 60.442,
            "bitrate": 651270.7058006022,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 576,
                "resolution_y": 1024,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 29.97
            }
        }
    },
    {
        "id": 833,
        "uuid": "39a21ded-9cee-43b0-b0a5-371221013dd4",
        "user_id": 4260,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/833-6371c4f759d48.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/833-6371c4f5d25cf.mp4",
        "description": "Khoái Khoái :))",
        "music": "",
        "is_liked": false,
        "likes_count": 8,
        "comments_count": 0,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [
            "comment"
        ],
        "published_at": "2022-11-14 11:32:53",
        "created_at": "2022-11-14 11:32:53",
        "updated_at": "2022-11-14 11:32:56",
        "user": {
            "id": 4260,
            "first_name": "Gumball",
            "last_name": "Waterson",
            "nickname": "vietit0103",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/4260/6371c33c2c1d9.png",
            "bio": "I'm the best",
            "tick": false,
            "is_followed": false,
            "followings_count": 5,
            "followers_count": 9,
            "likes_count": 8,
            "website_url": "https://fullstack.edu.vn/",
            "facebook_url": "",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 3082207,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "0:15",
            "playtime_seconds": 15.093,
            "bitrate": 1624371.0329291725,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 576,
                "resolution_y": 1024,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 30
            }
        }
    },
    {
        "id": 832,
        "uuid": "c7d8663d-f174-4cf0-9bc9-754da6162811",
        "user_id": 3998,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/832-6371c2f4acfc9.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/832-6371c2f456660.mp4",
        "description": "Siuuuuuuuuuuu",
        "music": "Siuuuuuuuuuuu",
        "is_liked": false,
        "likes_count": 2,
        "comments_count": 2,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [],
        "published_at": "2022-11-14 11:24:20",
        "created_at": "2022-11-14 11:24:20",
        "updated_at": "2022-11-14 11:24:21",
        "user": {
            "id": 3998,
            "first_name": "Trần",
            "last_name": "Toàn",
            "nickname": "tranhuutoan",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/3998/63650b54826f3.jpg",
            "bio": "https://github.com/htoann/tiktok-clone",
            "tick": false,
            "is_followed": false,
            "followings_count": 12,
            "followers_count": 11,
            "likes_count": 16,
            "website_url": "",
            "facebook_url": "",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 4984550,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "1:00",
            "playtime_seconds": 60.442,
            "bitrate": 651270.7058006022,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 576,
                "resolution_y": 1024,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 29.97
            }
        }
    },
    {
        "id": 831,
        "uuid": "ca70c330-e202-4a10-86c8-e3d198f0cc55",
        "user_id": 3927,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/831-6371b6ac39be5.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/831-6371b6ab8d6b2.mp4",
        "description": "Baybe #fixx",
        "music": "BBaayybbee",
        "is_liked": false,
        "likes_count": 4,
        "comments_count": 1,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [],
        "published_at": "2022-11-14 10:31:55",
        "created_at": "2022-11-14 10:31:55",
        "updated_at": "2022-11-14 10:31:56",
        "user": {
            "id": 3927,
            "first_name": "so",
            "last_name": "Tiredddd",
            "nickname": "beona",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/3927/636e0987a43ae.jpg",
            "bio": "siu cấp trầm cảmm",
            "tick": false,
            "is_followed": false,
            "followings_count": 15,
            "followers_count": 12,
            "likes_count": 35,
            "website_url": "https://fullstack.edu.vn/",
            "facebook_url": "",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 1346811,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "0:11",
            "playtime_seconds": 11.191,
            "bitrate": 953184.5232776337,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 576,
                "resolution_y": 1024,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 30
            }
        }
    },
    {
        "id": 830,
        "uuid": "e25f57e6-7c38-4f3c-9422-05de0b5115bd",
        "user_id": 4027,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/830-6371b1de464e9.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/830-6371b1dd6ce2d.mp4",
        "description": "F I N A L #final",
        "music": "",
        "is_liked": false,
        "likes_count": 3,
        "comments_count": 2,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [
            "comment"
        ],
        "published_at": "2022-11-14 10:11:25",
        "created_at": "2022-11-14 10:11:25",
        "updated_at": "2022-11-14 10:11:27",
        "user": {
            "id": 4027,
            "first_name": "Bẻo nà",
            "last_name": "Nà",
            "nickname": "k",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/4027/636e053e25ee8.jpg",
            "bio": "Siu cấp trầm cảm",
            "tick": false,
            "is_followed": true,
            "followings_count": 1,
            "followers_count": 4,
            "likes_count": 3,
            "website_url": "https://fullstack.edu.vn/",
            "facebook_url": "",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 2052803,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "0:11",
            "playtime_seconds": 10.889,
            "bitrate": 1498520.7089723574,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 576,
                "resolution_y": 1024,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 30
            }
        }
    },
    {
        "id": 597,
        "uuid": "ace8d662-9ede-47f1-b129-fe022d5a1d69",
        "user_id": 4153,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/597-6366c700ba4c4.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/597-6366c6ff954f6.mp4",
        "description": "FB: Trần Văn Đông (ig:dong180320)",
        "music": "",
        "is_liked": false,
        "likes_count": 9,
        "comments_count": 12,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [
            "comment"
        ],
        "published_at": "2022-11-06 03:26:39",
        "created_at": "2022-11-06 03:26:39",
        "updated_at": "2022-11-06 03:26:59",
        "user": {
            "id": 4153,
            "first_name": "Trần Văn",
            "last_name": "Đông",
            "nickname": "trandong1803",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/4153/6366c4a9204d9.jpg",
            "bio": "✨ 2000✨\nVietnam 🇻🇳\nTrần Văn Đông  !",
            "tick": false,
            "is_followed": false,
            "followings_count": 4,
            "followers_count": 11,
            "likes_count": 9,
            "website_url": "https://fullstack.edu.vn/",
            "facebook_url": "",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 12899208,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "1:06",
            "playtime_seconds": 66.362,
            "bitrate": 1546316.7475362408,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 576,
                "resolution_y": 1024,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 29.97
            }
        }
    },
    {
        "id": 596,
        "uuid": "9c0c14a1-a260-4501-b3fb-ccd02e1ec89d",
        "user_id": 211,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/596-63667ad1ce86a.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/596-63667ad145446.mp4",
        "description": "Hutao 3m084, quên k kéo setting nên vẫn để đồ lỏ 🥲 #hutao#genshin#genshinimpact",
        "music": "nhạc nền - mad",
        "is_liked": false,
        "likes_count": 2,
        "comments_count": 6,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [
            "comment",
            "duet",
            "stitch"
        ],
        "published_at": "2022-11-05 22:01:37",
        "created_at": "2022-11-05 22:01:37",
        "updated_at": "2022-11-05 22:01:39",
        "user": {
            "id": 211,
            "first_name": "Đỗ",
            "last_name": "Xuân Bách",
            "nickname": "xuanbachdev",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/211/63667b3246f40.jpg",
            "bio": "Xuanbach.dev",
            "tick": false,
            "is_followed": true,
            "followings_count": 7,
            "followers_count": 47,
            "likes_count": 40,
            "website_url": "https://fullstack.edu.vn/",
            "facebook_url": "https://www.facebook.com/xuanbachh.dev",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 6481334,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "0:16",
            "playtime_seconds": 16.182,
            "bitrate": 3195104.189840564,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 1246,
                "resolution_y": 576,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 60
            }
        }
    },
    {
        "id": 595,
        "uuid": "d467efcd-7739-44a1-a9e3-2bf7690dd281",
        "user_id": 211,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/595-63667a82c0c56.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/595-63667a8256d03.mp4",
        "description": "https://www.tiktok-ui.tk/",
        "music": "nhạc nền - mad",
        "is_liked": false,
        "likes_count": 5,
        "comments_count": 7,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [
            "comment",
            "duet",
            "stitch"
        ],
        "published_at": "2022-11-05 22:00:18",
        "created_at": "2022-11-05 22:00:18",
        "updated_at": "2022-11-05 22:00:20",
        "user": {
            "id": 211,
            "first_name": "Đỗ",
            "last_name": "Xuân Bách",
            "nickname": "xuanbachdev",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/211/63667b3246f40.jpg",
            "bio": "Xuanbach.dev",
            "tick": false,
            "is_followed": false,
            "followings_count": 7,
            "followers_count": 47,
            "likes_count": 40,
            "website_url": "https://fullstack.edu.vn/",
            "facebook_url": "https://www.facebook.com/xuanbachh.dev",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 1609433,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "0:10",
            "playtime_seconds": 9.519,
            "bitrate": 1343206.6393528732,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 576,
                "resolution_y": 1024,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 30
            }
        }
    },
    {
        "id": 593,
        "uuid": "9d04603c-b253-4b66-99f8-a606a41a5b8b",
        "user_id": 3998,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/593-6365efca55116.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/593-6365efc96ad9b.mp4",
        "description": "https://github.com/htoann/tiktok-clone",
        "music": "Tích cực commit, vận may sẽ đến",
        "is_liked": false,
        "likes_count": 4,
        "comments_count": 4,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [
            "comment",
            "duet",
            "stitch"
        ],
        "published_at": "2022-11-05 12:08:25",
        "created_at": "2022-11-05 12:08:25",
        "updated_at": "2022-11-05 12:08:27",
        "user": {
            "id": 3998,
            "first_name": "Trần",
            "last_name": "Toàn",
            "nickname": "tranhuutoan",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/3998/63650b54826f3.jpg",
            "bio": "https://github.com/htoann/tiktok-clone",
            "tick": false,
            "is_followed": false,
            "followings_count": 12,
            "followers_count": 11,
            "likes_count": 16,
            "website_url": "",
            "facebook_url": "",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 983111,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "0:08",
            "playtime_seconds": 8.034,
            "bitrate": 978902.6636793626,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 608,
                "resolution_y": 1080,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 30
            }
        }
    },
    {
        "id": 591,
        "uuid": "98f9b610-e211-47d2-9fc9-ebc4108b71bd",
        "user_id": 4150,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/591-6365c77d81b60.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/591-6365c77cdcfe0.mp4",
        "description": "F8 Nhà cái hàng đầu Châu Á",
        "music": "Lonely - Nhậc Cò",
        "is_liked": false,
        "likes_count": 4,
        "comments_count": 0,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [
            "comment"
        ],
        "published_at": "2022-11-05 09:16:28",
        "created_at": "2022-11-05 09:16:28",
        "updated_at": "2022-11-05 09:16:31",
        "user": {
            "id": 4150,
            "first_name": "Miles",
            "last_name": "Nguyen",
            "nickname": "truong9067",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/4150/6365c3d9d288c.jpg",
            "bio": "Akira",
            "tick": false,
            "is_followed": false,
            "followings_count": 4,
            "followers_count": 6,
            "likes_count": 8,
            "website_url": "https://tiktok-ui-miles.vercel.app/",
            "facebook_url": "https://www.facebook.com/ntt.miles",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 4585321,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "0:21",
            "playtime_seconds": 20.642513020833334,
            "bitrate": 1773561.5795930855,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 1280,
                "resolution_y": 720,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 30
            }
        }
    },
    {
        "id": 590,
        "uuid": "23e95a9f-e433-4702-8e8f-4068eb7d90c1",
        "user_id": 4150,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/590-6365c6ec1606f.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/590-6365c6eb9dec1.mp4",
        "description": "https://tiktok-ui-miles.vercel.app/",
        "music": "Lonely - Nhậc Cò",
        "is_liked": false,
        "likes_count": 4,
        "comments_count": 2,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [
            "comment"
        ],
        "published_at": "2022-11-05 09:14:03",
        "created_at": "2022-11-05 09:14:03",
        "updated_at": "2022-11-05 09:14:05",
        "user": {
            "id": 4150,
            "first_name": "Miles",
            "last_name": "Nguyen",
            "nickname": "truong9067",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/4150/6365c3d9d288c.jpg",
            "bio": "Akira",
            "tick": false,
            "is_followed": false,
            "followings_count": 4,
            "followers_count": 6,
            "likes_count": 8,
            "website_url": "https://tiktok-ui-miles.vercel.app/",
            "facebook_url": "https://www.facebook.com/ntt.miles",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 2699939,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "0:19",
            "playtime_seconds": 18.925,
            "bitrate": 1132170.145310436,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 576,
                "resolution_y": 1024,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 30
            }
        }
    },
    {
        "id": 589,
        "uuid": "32abf158-6337-4d5a-bfc1-176cc705e76e",
        "user_id": 4149,
        "type": "",
        "thumb_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/589-636554f8eb786.jpg",
        "file_url": "https://files.fullstack.edu.vn/f8-tiktok/videos/589-636554f7f347a.mp4",
        "description": "công nghệ thông tin ở Việt Nam như thế nào",
        "music": "",
        "is_liked": false,
        "likes_count": 2,
        "comments_count": 1,
        "shares_count": 0,
        "views_count": 0,
        "viewable": "public",
        "allows": [
            "comment"
        ],
        "published_at": "2022-11-05 01:07:51",
        "created_at": "2022-11-05 01:07:51",
        "updated_at": "2022-11-05 01:07:55",
        "user": {
            "id": 4149,
            "first_name": "Trần Mạnh",
            "last_name": "Hùng",
            "nickname": "hungtran",
            "avatar": "https://files.fullstack.edu.vn/f8-tiktok/users/4149/63654ffc2af12.jpg",
            "bio": "Rể 38. Yêu em không bao giờ là đủ. Real love is you 😘",
            "tick": false,
            "is_followed": false,
            "followings_count": 3,
            "followers_count": 4,
            "likes_count": 2,
            "website_url": "https://fullstack.edu.vn/",
            "facebook_url": "",
            "youtube_url": "",
            "twitter_url": "",
            "instagram_url": ""
        },
        "meta": {
            "file_size": 9917225,
            "file_format": "mp4",
            "mime_type": "video/mp4",
            "playtime_string": "2:11",
            "playtime_seconds": 131.204,
            "bitrate": 597904.2102374927,
            "video": {
                "dataformat": "quicktime",
                "rotate": 0,
                "resolution_x": 576,
                "resolution_y": 1024,
                "fourcc": "avc1",
                "fourcc_lookup": "H.264/MPEG-4 AVC",
                "frame_rate": 25
            }
        }
    }


]